import json

OUTPUT = '/home/runner/work/DsaTracker/DsaTracker/dsa_tracker.html'

patterns = [
  {"id":1,"name":"Sliding Window","learn":[
    {"name":"Maximum Sum Subarray of Size K","lc":643,"diff":"easy","tip":"Fixed window: keep running sum, subtract arr[i-K] and add arr[i]. Track maximum sum. O(n) time, O(1) space."},
    {"name":"Longest Substring Without Repeating Characters","lc":3,"diff":"medium","tip":"Expand right, shrink left when duplicate found via HashSet. O(n) time, O(min(n,m)) space."},
    {"name":"Fruit Into Baskets","lc":904,"diff":"medium","tip":"At most 2 distinct values in window. HashMap tracks counts. Shrink left when map size>2. O(n) time, O(1) space."},
    {"name":"Permutation in String","lc":567,"diff":"medium","tip":"Fixed window=len(s1). Compare freq arrays. Shrink/expand by one char each step. O(n) time, O(1) space."},
    {"name":"Find All Anagrams in a String","lc":438,"diff":"medium","tip":"Same as LC 567 but collect all valid start indices. Freq array comparison each step. O(n) time, O(1) space."},
    {"name":"Longest Repeating Character Replacement","lc":424,"diff":"medium","tip":"Key: maxFreq+K>=windowSize means valid. Never shrink maxFreq. O(n) time, O(1) space."},
    {"name":"Longest Substring with At Most K Distinct Characters","lc":340,"diff":"medium","tip":"HashMap char->count. Shrink left when map size>K, decrement count, remove if zero. O(n) time, O(K) space."},
    {"name":"Grumpy Bookstore Owner","lc":1052,"diff":"medium","tip":"Base = always-satisfied customers. Sliding window of size 'minutes' finds max extra grumpy gain. O(n) time, O(1) space."},
    {"name":"Maximum Points You Can Obtain from Cards","lc":1423,"diff":"medium","tip":"Take k from ends = minimize middle subarray of length n-k. Sliding window on middle. O(n) time, O(1) space."},
    {"name":"Minimum Difference Between Highest and Lowest of K Scores","lc":1984,"diff":"easy","tip":"Sort first. Minimum range of k consecutive sorted elements. Window size k, answer=arr[i+k-1]-arr[i]. O(n log n) time."},
    {"name":"Diet Plan Performance","lc":1176,"diff":"easy","tip":"Fixed window size k on calories. Compare sum to lower/upper bounds each step. O(n) time, O(1) space."}
  ],"practice":[
    {"name":"Minimum Window Substring","lc":76,"diff":"hard","tip":"Expand right until valid (all chars present), shrink left to minimize. 'formed' counter tracks validity. O(n+m) time."},
    {"name":"Sliding Window Maximum","lc":239,"diff":"hard","tip":"Monotonic decreasing deque of indices. Remove back if smaller than new, remove front if out of window. Front=max. O(n) time, O(k) space."},
    {"name":"Max Consecutive Ones III","lc":1004,"diff":"medium","tip":"Window with at most K zeros. When zeroCount>K shrink from left. Max window size is answer. O(n) time, O(1) space."},
    {"name":"Subarray Product Less Than K","lc":713,"diff":"medium","tip":"Variable window: divide by left when product>=k. Subarrays ending at right=right-left+1. O(n) time, O(1) space."},
    {"name":"Number of Subarrays with Bounded Maximum","lc":795,"diff":"medium","tip":"f(bound)=count subarrays with max<=bound. Answer=f(R)-f(L-1). Each uses sliding window with running length. O(n) time."},
    {"name":"Minimum Size Subarray Sum","lc":209,"diff":"medium","tip":"Expand right adding to sum, shrink left when sum>=target. Track min window size. O(n) time, O(1) space."},
    {"name":"Longest Turbulent Subarray","lc":978,"diff":"medium","tip":"Track current turbulent run length. Reset on equal consecutive elements, extend on alternating. O(n) time, O(1) space."},
    {"name":"Binary Subarrays With Sum","lc":930,"diff":"medium","tip":"Exactly goal = atMost(goal)-atMost(goal-1). Standard variable sliding window for each atMost. O(n) time."},
    {"name":"Count Number of Nice Subarrays","lc":1248,"diff":"medium","tip":"Exactly k odds = atMost(k)-atMost(k-1). Or prefix odd-count + HashMap. O(n) time, O(n) space."},
    {"name":"Minimum Operations to Reduce X to Zero","lc":1658,"diff":"medium","tip":"Equivalent: find max subarray with sum=total-x. Sliding window for max length subarray. O(n) time, O(1) space."},
    {"name":"Longest Subarray of 1s After Deleting One Element","lc":1493,"diff":"medium","tip":"Window with at most one zero. Shrink when zeros>1. Answer=maxWindow-1 (mandatory deletion). O(n) time, O(1) space."},
    {"name":"Get Equal Substrings Within Budget","lc":1208,"diff":"medium","tip":"Cost[i]=|s[i]-t[i]|. Max window with total cost<=maxCost. Standard variable sliding window. O(n) time."},
    {"name":"Frequency of the Most Frequent Element","lc":1838,"diff":"medium","tip":"Sort. Window: ops needed=k*right-windowSum. Shrink if ops>k. Max valid window is answer. O(n log n) time."},
    {"name":"Replace the Substring for Balanced String","lc":1234,"diff":"medium","tip":"Chars outside window must not exceed n/4 each. Shrink window while condition holds. O(n) time, O(1) space."}
  ],"hard":[
    {"name":"Substring with Concatenation of All Words","lc":30,"diff":"hard","tip":"Sliding window of size wordLen*numWords. Extract words, compare against frequency map. Reset on bad word. O(n*m*L) time."},
    {"name":"Minimum Window Subsequence","lc":727,"diff":"hard","tip":"Forward scan to find window covering T, then shrink from left to minimize. Repeat for all valid windows. O(mn) time."},
    {"name":"Subarrays with K Different Integers","lc":992,"diff":"hard","tip":"Exactly K = atMost(K)-atMost(K-1). Each atMost is standard variable sliding window with HashMap. O(n) time."},
    {"name":"Minimum Number of K Consecutive Bit Flips","lc":995,"diff":"hard","tip":"Greedy: flip leftmost 0. Difference array tracks flips without re-applying. Check current bit XOR flip parity. O(n) time."},
    {"name":"Shortest Subarray with Sum at Least K","lc":862,"diff":"hard","tip":"Prefix sums + monotonic deque. For each right, pop front while prefix[right]-prefix[front]>=k. Push in order. O(n) time."}
  ]},
  {"id":2,"name":"Prefix Sum","learn":[
    {"name":"Range Sum Query - Immutable","lc":303,"diff":"easy","tip":"prefix[i]=prefix[i-1]+nums[i]. Range [l,r]=prefix[r]-prefix[l-1]. O(n) build, O(1) query, O(n) space."},
    {"name":"Find Pivot Index","lc":724,"diff":"easy","tip":"leftSum = total - nums[i] - leftSum gives rightSum. Check equality at each index. O(n) time, O(1) space."},
    {"name":"Running Sum of 1d Array","lc":1480,"diff":"easy","tip":"Each element becomes sum of all previous elements plus itself. Simple in-place prefix sum. O(n) time, O(1) extra space."},
    {"name":"Product of Array Except Self","lc":238,"diff":"medium","tip":"Left pass: product of all left elements. Right pass: multiply by product of right elements. No division. O(n) time, O(1) extra space."},
    {"name":"Subarray Sum Equals K","lc":560,"diff":"medium","tip":"HashMap stores prefix sum frequencies. For current sum, if (sum-k) in map, add its count. O(n) time, O(n) space."},
    {"name":"Contiguous Array","lc":525,"diff":"medium","tip":"Replace 0s with -1. Longest subarray with sum=0 via prefix sum + HashMap. Same prefix at two indices = zero-sum between them. O(n)."},
    {"name":"Subarray Sums Divisible by K","lc":974,"diff":"medium","tip":"Prefix sum mod K. Two same-mod indices mean divisible subarray between them. Count pairs via frequency array. O(n) time."},
    {"name":"Sum of Even Numbers After Queries","lc":985,"diff":"medium","tip":"Track current even sum. Per query: adjust even sum based on old/new value parities. O(n+q) time, O(1) space."},
    {"name":"Minimum Value to Get Positive Step by Step Sum","lc":1413,"diff":"easy","tip":"Find minimum prefix sum. Answer = max(1, 1 - minPrefixSum). O(n) time, O(1) space."},
    {"name":"Left and Right Sum Differences","lc":2574,"diff":"easy","tip":"Compute prefix sums from left and suffix from right. diff[i]=|leftSum[i]-rightSum[i]|. O(n) time, O(n) space."},
    {"name":"Find the Middle Index in Array","lc":1991,"diff":"easy","tip":"Same as pivot index. leftSum == total-leftSum-nums[i]. Running sum approach. O(n) time, O(1) space."}
  ],"practice":[
    {"name":"Range Sum Query 2D - Immutable","lc":304,"diff":"medium","tip":"2D prefix: prefix[i][j]=sum of rectangle (0,0)-(i,j). Query using inclusion-exclusion on 4 corners. O(mn) build, O(1) query."},
    {"name":"Path Sum III","lc":437,"diff":"medium","tip":"DFS with running path sum. HashMap of prefix sum counts. For each node, (currSum-target) in map gives valid paths. O(n) time."},
    {"name":"Maximum Size Subarray Sum Equals K","lc":325,"diff":"medium","tip":"HashMap stores first occurrence of each prefix sum. For each index, check (sum-k) for max length. O(n) time, O(n) space."},
    {"name":"Continuous Subarray Sum","lc":523,"diff":"medium","tip":"Prefix mod k. Same remainder at two indices with gap>=2 means valid subarray. Store first occurrence. O(n) time, O(k) space."},
    {"name":"Count of Range Sum","lc":327,"diff":"hard","tip":"Merge sort prefix sums. During merge, count pairs where lower<=prefix[j]-prefix[i]<=upper. O(n log n) time, O(n) space."},
    {"name":"Number of Ways to Split Array","lc":2270,"diff":"medium","tip":"Prefix sum array. For each split, check if leftSum>=rightSum. Count valid splits. O(n) time, O(n) space."},
    {"name":"Ways to Make a Fair Array","lc":1664,"diff":"medium","tip":"Prefix odd/even index sums. Removing index i recalculates parity contributions. Check if array becomes fair. O(n) time."},
    {"name":"Minimum Average Difference","lc":2256,"diff":"medium","tip":"Prefix sum for left average, suffix for right. Minimize |leftAvg-rightAvg|. Handle empty right part. O(n) time."},
    {"name":"Sum of Absolute Differences in a Sorted Array","lc":1685,"diff":"medium","tip":"For sorted array: result[i]=i*nums[i]-prefix[i] + (suffix[i]-(n-i)*nums[i]). Prefix sums. O(n) time."},
    {"name":"Make Sum Divisible by P","lc":1590,"diff":"medium","tip":"Remove shortest subarray with sum = total mod p. Prefix mod HashMap. O(n) time, O(n) space."},
    {"name":"K-Radius Subarray Averages","lc":2090,"diff":"medium","tip":"Prefix sum for range queries. Center i with full 2k+1 window: avg from prefix[i+k+1]-prefix[i-k]. O(n) time."},
    {"name":"Maximum Subarray Sum with One Deletion","lc":1186,"diff":"medium","tip":"DP: endHere=max subarray ending here (no deletion), endHereDel=max with one deletion. O(n) time, O(1) space."},
    {"name":"Number of Smooth Descent Periods of a Stock","lc":2110,"diff":"easy","tip":"Count consecutive run lengths where each step decreases by 1. Run of length L contributes L*(L+1)/2. O(n) time."},
    {"name":"Corporate Flight Bookings","lc":1109,"diff":"medium","tip":"Difference array: +seats at from-1, -seats at to. Prefix sum of difference array = actual bookings per flight. O(n+b)."}
  ],"hard":[
    {"name":"Count of Smaller Numbers After Self","lc":315,"diff":"hard","tip":"Merge sort or BIT/Fenwick tree. Count inversions during merge (elements to right that are smaller). O(n log n) time."},
    {"name":"Maximum Sum of 3 Non-Overlapping Subarrays","lc":689,"diff":"hard","tip":"Precompute window sums. Build left[]/right[] arrays for best window index up to/from each position. O(n) time."},
    {"name":"Number of Subarrays with Bounded Maximum","lc":795,"diff":"medium","tip":"f(R)-f(L-1) where f(b)=count subarrays with max<=b. Compute using running length segments split at >b. O(n) time."},
    {"name":"Count of Range Sum (Hard)","lc":327,"diff":"hard","tip":"Augmented merge sort on prefix sums. Count pairs in [lower,upper] during merge with two pointers. O(n log n) time."},
    {"name":"Minimum Cost to Merge Stones","lc":1000,"diff":"hard","tip":"Interval DP: dp[i][j]=min cost to merge stones[i..j]. Merge k groups at a time. Prefix sums for range queries. O(n^3/k) time."}
  ]},
  {"id":3,"name":"Two Pointers","learn":[
    {"name":"Valid Palindrome","lc":125,"diff":"easy","tip":"Two pointers from both ends. Skip non-alphanumeric, compare lowercase chars. O(n) time, O(1) space."},
    {"name":"Two Sum II - Input Array Is Sorted","lc":167,"diff":"medium","tip":"Left+right>target: right--. Left+right<target: left++. Equal: found. O(n) time, O(1) space."},
    {"name":"Remove Duplicates from Sorted Array","lc":26,"diff":"easy","tip":"Slow pointer = insertion position. Fast scans for new values. Copy when different from slow. O(n) time, O(1) space."},
    {"name":"Move Zeroes","lc":283,"diff":"easy","tip":"Slow tracks next non-zero position. Fast scans. Swap non-zeros to front. O(n) time, O(1) space."},
    {"name":"Sort Colors","lc":75,"diff":"medium","tip":"Dutch National Flag: lo/mid/hi pointers. Swap 0s to front, 2s to back. O(n) time, O(1) space."},
    {"name":"Container With Most Water","lc":11,"diff":"medium","tip":"Move shorter wall inward. Greedy: moving taller can only decrease water. O(n) time, O(1) space."},
    {"name":"3Sum","lc":15,"diff":"medium","tip":"Sort, fix i, two pointers for remaining two. Skip duplicates at all three positions. O(n^2) time."},
    {"name":"Merge Sorted Array","lc":88,"diff":"easy","tip":"Fill from back: compare largest of both, place at end. Avoids overwriting. O(m+n) time, O(1) space."},
    {"name":"Reverse String","lc":344,"diff":"easy","tip":"Two pointers from both ends, swap until they meet. In-place modification. O(n) time, O(1) space."},
    {"name":"Is Subsequence","lc":392,"diff":"easy","tip":"Pointer on s advances only on match. Pointer on t always advances. Check if s pointer reaches end. O(n) time."},
    {"name":"Assign Cookies","lc":455,"diff":"easy","tip":"Sort both arrays. Greedily assign smallest sufficient cookie. Two pointers advance when child satisfied. O(n log n)."}
  ],"practice":[
    {"name":"Trapping Rain Water","lc":42,"diff":"hard","tip":"Two pointers. Water at i = min(maxLeft,maxRight)-height[i]. Track running max from both sides. O(n) time, O(1) space."},
    {"name":"4Sum","lc":18,"diff":"medium","tip":"Sort, fix i and j (nested), two pointers for remaining two. Skip all duplicates. O(n^3) time, O(1) extra space."},
    {"name":"Remove Duplicates from Sorted Array II","lc":80,"diff":"medium","tip":"Allow at most 2 copies. Compare with nums[slow-2]. If different, keep. O(n) time, O(1) space."},
    {"name":"3Sum Closest","lc":16,"diff":"medium","tip":"Sort. Fix i, two-pointer sum. Track min abs difference. O(n^2) time, O(1) space."},
    {"name":"Squares of a Sorted Array","lc":977,"diff":"easy","tip":"Two pointers from both ends. Larger square goes to end of result. Fill from back. O(n) time."},
    {"name":"Backspace String Compare","lc":844,"diff":"easy","tip":"Two pointers from end. Count backspaces, skip characters accordingly. O(n) time, O(1) space."},
    {"name":"Long Pressed Name","lc":925,"diff":"easy","tip":"Two pointers: advance both on match. If typed has same char (long press), advance typed only. O(n) time."},
    {"name":"Minimum Difference Between Highest and Lowest of K Scores","lc":1984,"diff":"easy","tip":"Sort. Window of k elements. Min difference = min(arr[i+k-1]-arr[i]). O(n log n) time."},
    {"name":"Number of Subsequences That Satisfy the Given Sum Condition","lc":1498,"diff":"medium","tip":"Sort. Fix left, find rightmost valid right. Count = 2^(right-left). Precompute powers. O(n log n) time."},
    {"name":"Boats to Save People","lc":881,"diff":"medium","tip":"Sort. Pair heaviest with lightest if sum<=limit. Two pointers converge. O(n log n) time, O(1) space."},
    {"name":"Sum of Square Numbers","lc":633,"diff":"medium","tip":"Two pointers: a=0, b=sqrt(c). Move a right or b left until found or crossed. O(sqrt(c)) time."},
    {"name":"Flipping an Image","lc":832,"diff":"easy","tip":"Two-pointer flip and invert: if ends equal both change, if different both stay. O(n^2) time, O(1) space."},
    {"name":"Find the Distance Value Between Two Arrays","lc":1385,"diff":"easy","tip":"Sort arr2. Binary search for each arr1 element: check if any arr2 element within d. O(n log m) time."},
    {"name":"Count Pairs Whose Sum is Less than Target","lc":2824,"diff":"easy","tip":"Sort. Two pointers: sum<target means all [left+1..right] pairs valid, add right-left. O(n log n) time."}
  ],"hard":[
    {"name":"Trapping Rain Water II","lc":407,"diff":"hard","tip":"Min-heap (priority queue). Process cells from smallest boundary inward. Water = maxBoundary - cellHeight. O(mn log(mn))."},
    {"name":"Minimum Window Substring","lc":76,"diff":"hard","tip":"Expand right until valid (all chars), shrink left to minimize. Track 'formed' count. O(n+m) time, O(n+m) space."},
    {"name":"Maximize the Confusion of an Exam","lc":2024,"diff":"medium","tip":"Sliding window twice: once for max T flips, once for max F flips. Take max of both runs. O(n) time."},
    {"name":"Minimize Maximum Pair Sum in Array","lc":1877,"diff":"medium","tip":"Sort. Pair smallest with largest: pairs are (nums[0],nums[n-1])... Min max pair sum via this greedy. O(n log n)."},
    {"name":"Partition Array Such That Maximum Difference Is K","lc":2294,"diff":"medium","tip":"Sort. Greedily form partitions: start new when current-partitionStart>k. Count partitions. O(n log n) time."}
  ]},
  {"id":4,"name":"Fast & Slow Pointers","learn":[
    {"name":"Linked List Cycle","lc":141,"diff":"easy","tip":"Floyd's: slow moves 1, fast moves 2. If they meet, cycle exists. If fast reaches null, no cycle. O(n) time, O(1) space."},
    {"name":"Linked List Cycle II","lc":142,"diff":"medium","tip":"After detecting cycle, reset one pointer to head. Both move 1 step. They meet at cycle start. O(n) time, O(1) space."},
    {"name":"Middle of the Linked List","lc":876,"diff":"easy","tip":"Slow moves 1, fast moves 2. When fast reaches end, slow is at middle. O(n) time, O(1) space."},
    {"name":"Happy Number","lc":202,"diff":"easy","tip":"Treat digit-square-sum as linked list. Floyd's detects cycle=not happy. Or detect reaching 1. O(log n) time."},
    {"name":"Palindrome Linked List","lc":234,"diff":"easy","tip":"Find middle with slow/fast. Reverse second half. Compare both halves. O(n) time, O(1) space."},
    {"name":"Find the Duplicate Number","lc":287,"diff":"medium","tip":"Treat as linked list: index->value. Floyd's detects cycle. Reset slow to 0, both move 1 step to find duplicate. O(n) time."},
    {"name":"Circular Array Loop","lc":457,"diff":"medium","tip":"For each start, slow/fast with same direction. Cycle valid if length>1 and consistent direction. O(n) time."},
    {"name":"Remove Nth Node From End of List","lc":19,"diff":"medium","tip":"Fast advances n steps first. Both move until fast.next=null. Slow.next is the node to remove. O(n) time."},
    {"name":"Delete the Middle Node of a Linked List","lc":2095,"diff":"medium","tip":"Slow/fast to find node before middle. Update slow.next=slow.next.next. O(n) time, O(1) space."},
    {"name":"Intersection of Two Linked Lists","lc":160,"diff":"easy","tip":"Two pointers: each traverses both lists (A then B, B then A). They meet at intersection or null. O(m+n) time."},
    {"name":"Number of Steps to Reduce a Number to Zero","lc":1342,"diff":"easy","tip":"If even divide by 2, if odd subtract 1. Count steps. Bit manipulation: popcount+(bitLen-1). O(log n) time."}
  ],"practice":[
    {"name":"Reorder List","lc":143,"diff":"medium","tip":"Find middle (slow/fast), reverse second half, merge two halves alternately. O(n) time, O(1) space."},
    {"name":"Remove Nth Node From End of List","lc":19,"diff":"medium","tip":"Fast leads by n steps. Move both until fast.next=null. Remove slow.next. Dummy head for edge cases. O(n)."},
    {"name":"Sort List","lc":148,"diff":"medium","tip":"Merge sort on linked list. Find middle (slow/fast), split, recursively sort, merge. O(n log n) time, O(log n) space."},
    {"name":"Rotate List","lc":61,"diff":"medium","tip":"Find length and tail. k=k%length. New tail at (length-k-1). Connect tail to head, cut at new tail. O(n) time."},
    {"name":"Delete the Middle Node of a Linked List","lc":2095,"diff":"medium","tip":"Fast advances 2, slow 1. When fast.next null or fast.next.next null, slow is before middle. O(n) time."},
    {"name":"Intersection of Two Linked Lists","lc":160,"diff":"easy","tip":"Redirect to other list on null. They synchronize and meet at intersection or both null. O(m+n) time."},
    {"name":"Maximum Twin Sum of a Linked List","lc":2130,"diff":"medium","tip":"Find middle, reverse second half, traverse both halves simultaneously. Max twin sum. O(n) time, O(1) space."},
    {"name":"Odd Even Linked List","lc":328,"diff":"medium","tip":"Collect odd-indexed then even-indexed nodes. Connect odd tail to even head. O(n) time, O(1) space."},
    {"name":"Swapping Nodes in a Linked List","lc":1721,"diff":"medium","tip":"Find kth from start (advance k-1). Find kth from end with two-pointer gap. Swap values. O(n) time."},
    {"name":"Find the Minimum and Maximum Number of Nodes Between Critical Points","lc":2058,"diff":"medium","tip":"Identify critical points (local min/max). Min = min of adjacent pair distances. Max = last-first critical. O(n)."},
    {"name":"Reverse Linked List","lc":206,"diff":"easy","tip":"Three pointers prev/curr/next. Save next, point curr to prev, advance both. O(n) time, O(1) space."},
    {"name":"Merge Two Sorted Lists","lc":21,"diff":"easy","tip":"Compare heads, take smaller. Advance that pointer. Attach remaining list. O(m+n) time, O(1) space."},
    {"name":"Split Linked List in Parts","lc":725,"diff":"medium","tip":"Length L, each part=L/k, first L%k parts get extra node. Traverse cutting at correct sizes. O(n+k) time."},
    {"name":"Convert Binary Number in a Linked List to Integer","lc":1290,"diff":"easy","tip":"Running total: result = result*2 + node.val. Single traversal. O(n) time, O(1) space."}
  ],"hard":[
    {"name":"LFU Cache","lc":460,"diff":"hard","tip":"Track min frequency. HashMap<freq, LinkedHashSet<key>>. On access, move key to next freq bucket and update min. O(1) all ops."},
    {"name":"Linked List Components","lc":817,"diff":"medium","tip":"Put G values in HashSet. Walk list: count component when node in set and previous wasn't. O(n) time."},
    {"name":"Split Linked List in Parts","lc":725,"diff":"medium","tip":"Length L. Each part = L/k nodes; first L%k get one extra. Walk list k times cutting at right spots. O(n+k)."},
    {"name":"Reverse Nodes in k-Group","lc":25,"diff":"hard","tip":"Check k nodes exist ahead. Reverse k nodes, connect prev group tail to new head, current tail to recursive result. O(n) time."},
    {"name":"Merge k Sorted Lists","lc":23,"diff":"hard","tip":"Min-heap of (value, listIndex, node). Pop smallest, push next from same list. O(N log k) time, O(k) space."}
  ]},
  {"id":5,"name":"LinkedList In-place Reversal","learn":[
    {"name":"Reverse Linked List","lc":206,"diff":"easy","tip":"Three pointers: prev=null, curr, next. Save next, reverse curr->prev, advance. O(n) time, O(1) space."},
    {"name":"Reverse Linked List II","lc":92,"diff":"medium","tip":"Advance to left. Reverse right-left+1 nodes. Reconnect with nodes before left and after right. O(n) time."},
    {"name":"Swap Nodes in Pairs","lc":24,"diff":"medium","tip":"Dummy head. Each pair: save nodes, rewire prev->second->first->next. Advance by 2. O(n) time, O(1) space."},
    {"name":"Reverse Nodes in k-Group","lc":25,"diff":"hard","tip":"Check k nodes exist. Reverse k nodes, connect previous group tail to new head. Recurse. O(n) time, O(n/k) stack."},
    {"name":"Reorder List","lc":143,"diff":"medium","tip":"Find middle (slow/fast), reverse second half, interleave first and reversed second. O(n) time, O(1) space."},
    {"name":"Rotate List","lc":61,"diff":"medium","tip":"Connect tail to head (circular), find new tail at length-k%length-1, cut there. O(n) time, O(1) space."},
    {"name":"Reverse Nodes in Even Length Groups","lc":2074,"diff":"medium","tip":"Walk through groups of size 1,2,3... Reverse groups with even actual count. O(n) time, O(1) space."},
    {"name":"Reverse String","lc":344,"diff":"easy","tip":"Two pointers swap from both ends moving inward. In-place. O(n) time, O(1) space."},
    {"name":"Reverse Words in a String","lc":151,"diff":"medium","tip":"Split by spaces, filter empty, reverse order, join with single space. Or reverse-all then reverse-each-word. O(n)."},
    {"name":"Reverse Words in a String III","lc":557,"diff":"easy","tip":"Split by spaces, reverse each word individually, rejoin. O(n) time, O(n) space."},
    {"name":"Reverse Only Letters","lc":917,"diff":"easy","tip":"Two pointers skip non-letters, swap letters only. O(n) time, O(n) for char array."}
  ],"practice":[
    {"name":"Palindrome Linked List","lc":234,"diff":"easy","tip":"Find middle with slow/fast, reverse second half, compare with first half. O(n) time, O(1) space."},
    {"name":"Odd Even Linked List","lc":328,"diff":"medium","tip":"Weave odd nodes, weave even nodes, connect odd tail to even head. O(n) time, O(1) space."},
    {"name":"Add Two Numbers","lc":2,"diff":"medium","tip":"Traverse both lists with carry. New node for each digit sum. Handle remaining carry at end. O(max(m,n)) time."},
    {"name":"Add Two Numbers II","lc":445,"diff":"medium","tip":"Reverse both lists, add like LC 2, reverse result. Or use stacks. O(m+n) time, O(m+n) space."},
    {"name":"Maximum Twin Sum of a Linked List","lc":2130,"diff":"medium","tip":"Find middle, reverse second half, compare twins from both ends. O(n) time, O(1) space."},
    {"name":"Swapping Nodes in a Linked List","lc":1721,"diff":"medium","tip":"Find kth from start (advance k). Find kth from end with two-pointer gap. Swap values. O(n) time."},
    {"name":"Sort List","lc":148,"diff":"medium","tip":"Merge sort: split at middle, sort each half, merge. O(n log n) time, O(log n) stack space."},
    {"name":"Reverse Prefix of Word","lc":2000,"diff":"easy","tip":"Find first occurrence of ch, reverse prefix up to that index. Two-pointer reverse. O(n) time, O(n) space."},
    {"name":"Insert Greatest Common Divisors in Linked List","lc":2807,"diff":"medium","tip":"Between each adjacent pair insert new node with GCD of their values. O(n log(maxVal)) time."},
    {"name":"Delete the Middle Node of a Linked List","lc":2095,"diff":"medium","tip":"Slow/fast pointer: slow reaches node before middle. Update slow.next. O(n) time."},
    {"name":"Rotate Array","lc":189,"diff":"medium","tip":"Reverse whole array, reverse first k, reverse remaining. In-place. O(n) time, O(1) space."},
    {"name":"Reverse Bits","lc":190,"diff":"easy","tip":"Process bit by bit: result=(result<<1)|(n&1), n>>=1. Repeat 32 times. O(1) time, O(1) space."},
    {"name":"Reverse String II","lc":541,"diff":"easy","tip":"Every 2k chars reverse first k. Handle last segment (<k: reverse all). O(n) time, O(n) space."},
    {"name":"Reverse Vowels of a String","lc":345,"diff":"easy","tip":"Two pointers skip non-vowels, swap vowels. O(n) time, O(n) space for char array."}
  ],"hard":[
    {"name":"Reverse Nodes in k-Group","lc":25,"diff":"hard","tip":"Check k nodes ahead exist before reversing. After reversing, connect prev group tail to new head and current tail to next group."},
    {"name":"Merge k Sorted Lists","lc":23,"diff":"hard","tip":"Min-heap of (value, node). Pop min, add to result, push next node from that list. O(N log k) time."},
    {"name":"Copy List with Random Pointer","lc":138,"diff":"medium","tip":"Interleave cloned nodes: A->A'->B->B'. Set random via node.next.random=node.random.next. Separate lists. O(n)."},
    {"name":"LRU Cache","lc":146,"diff":"medium","tip":"Doubly linked list + HashMap. Map=key->node. On access/insert move to front. On eviction remove from tail. O(1)."},
    {"name":"Design Linked List","lc":707,"diff":"medium","tip":"Dummy head and tail. For get/addAt traverse to index. addAtHead/Tail use dummies. O(n) get, O(1) add ends."}
  ]},
  {"id":6,"name":"Monotonic Stack","learn":[
    {"name":"Next Greater Element I","lc":496,"diff":"easy","tip":"Monotonic decreasing stack on nums2. Pop smaller elements, record their NGE. HashMap for O(1) lookup. O(n+m) time."},
    {"name":"Next Greater Element II","lc":503,"diff":"medium","tip":"Circular array: iterate 2n times using mod. Monotonic decreasing stack of indices. O(n) time, O(n) space."},
    {"name":"Daily Temperatures","lc":739,"diff":"medium","tip":"Monotonic decreasing stack of indices. When today>stackTop, pop and compute wait=today-popped. O(n) time."},
    {"name":"Online Stock Span","lc":901,"diff":"medium","tip":"Stack of (price, span). Pop while price<=top, accumulate spans. Push with total span. Amortized O(1) per call."},
    {"name":"Sum of Subarray Minimums","lc":907,"diff":"medium","tip":"Monotonic stack finds prev/next smaller bounds. Contribution of each element = elem * leftCount * rightCount. O(n)."},
    {"name":"Remove Duplicate Letters","lc":316,"diff":"medium","tip":"Greedy with monotonic stack. Pop larger char if it appears later. Only push if char not in stack. O(n) time."},
    {"name":"132 Pattern","lc":456,"diff":"medium","tip":"Scan right-to-left. Monotonic stack tracks candidates. Keep max popped element as the '2'. O(n) time."},
    {"name":"Next Greater Node In Linked List","lc":1019,"diff":"medium","tip":"Convert to array. Monotonic decreasing stack of (value, index). When larger found, fill result at stored index. O(n)."},
    {"name":"Final Prices With a Special Discount in a Shop","lc":1475,"diff":"easy","tip":"Monotonic non-decreasing stack. Current price<=stack top = discount. Pop on smaller/equal. O(n) time."},
    {"name":"Build an Array With Stack Operations","lc":1441,"diff":"easy","tip":"Simulate: push 1..n, pop if top!=target[i]. Advance target pointer on match. O(n) time, O(n) space."},
    {"name":"Maximum Width Ramp","lc":962,"diff":"medium","tip":"Decreasing stack from left. Sweep right-to-left: pop while A[top]<=A[j], update max=j-top. O(n) time."}
  ],"practice":[
    {"name":"Largest Rectangle in Histogram","lc":84,"diff":"hard","tip":"Monotonic increasing stack. Pop when current<top, height=popped, width=curr-newTop-1. Drain stack at end. O(n)."},
    {"name":"Trapping Rain Water","lc":42,"diff":"hard","tip":"Monotonic stack: when current>top, compute trapped=(min(heights)-bottom)*width. O(n) time, O(n) space."},
    {"name":"Maximal Rectangle","lc":85,"diff":"hard","tip":"Build histogram row by row. Apply largest rectangle in histogram on each row. O(mn) time, O(n) space."},
    {"name":"Number of Visible People in a Queue","lc":1944,"diff":"hard","tip":"Right-to-left monotonic decreasing stack. For each person count popped shorter ones + possible taller blocker. O(n)."},
    {"name":"Final Prices With a Special Discount in a Shop","lc":1475,"diff":"easy","tip":"Monotonic increasing stack. Pop when current<=top, apply discount. Push all. O(n) time, O(n) space."},
    {"name":"Asteroid Collision","lc":735,"diff":"medium","tip":"Stack simulation. Positive: push. Negative: pop positives until stable or absorbed. Handle same-size collisions. O(n)."},
    {"name":"Validate Stack Sequences","lc":946,"diff":"medium","tip":"Simulate: push from pushed array. After each push, pop while top matches popped sequence. Valid if empty at end. O(n)."},
    {"name":"Remove K Digits","lc":402,"diff":"medium","tip":"Monotonic increasing stack: pop larger digits before current (budget k). Remove from top if k>0 remaining. O(n)."},
    {"name":"Create Maximum Number","lc":321,"diff":"hard","tip":"Try all splits (i from nums1, k-i from nums2). Find max subsequence each length, merge for max. O(k(m+n+k)) time."},
    {"name":"Decode String","lc":394,"diff":"medium","tip":"Stack of (repeatCount, currentString). On '[': push state. On ']': pop and repeat string. O(n) time, O(n) space."},
    {"name":"Score of Parentheses","lc":856,"diff":"medium","tip":"Stack: push 0 for '('. For ')': pop v, score=1 if v==0 else 2v. Add to new stack top. O(n) time."},
    {"name":"Minimum Stack","lc":155,"diff":"medium","tip":"Auxiliary min stack. Push to aux when new value<=current min. Pop aux when popping min. O(1) all ops."},
    {"name":"Number of Atoms","lc":726,"diff":"hard","tip":"Stack of HashMaps. On '(': push new map. On ')': pop, multiply by count, merge into current top. Sort alphabetically. O(n^2)."},
    {"name":"Sum of Subarray Ranges","lc":2104,"diff":"medium","tip":"Range=max-min. Sum of ranges = sum of subarray maxes - sum of mins. Each part solved with monotonic stack. O(n)."}
  ],"hard":[
    {"name":"Largest Rectangle in Histogram","lc":84,"diff":"hard","tip":"Push bar indices onto a monotonic increasing stack. When current < stack top, pop and compute area: height[popped]*(current-stackTop-1). Drain at end."},
    {"name":"Maximum Width Ramp","lc":962,"diff":"medium","tip":"Build a decreasing stack of indices from left. Then sweep right-to-left: while stackTop<=A[j], pop and update max width=j-stackTop."},
    {"name":"Number of People That Can Be Seen in a Grid","lc":2282,"diff":"hard","tip":"Process each row right to left with decreasing monotonic stack. Count visible before blocked by taller. O(mn) time."},
    {"name":"Maximal Rectangle","lc":85,"diff":"hard","tip":"For each row update heights array (histogram bars). Apply LC 84 algorithm using monotonic stack. O(mn) time, O(n) space."},
    {"name":"Sum of Subarray Ranges","lc":2104,"diff":"medium","tip":"Key insight: range=max-min. Sum of all ranges = sum of all subarray maxes minus sum of all mins. Both O(n) with monotonic stack."}
  ]},
  {"id":7,"name":"Top K Elements","learn":[
    {"name":"Kth Largest Element in an Array","lc":215,"diff":"medium","tip":"Min-heap of size k. Iterate: push, pop if size>k. Heap top is kth largest. O(n log k) time, O(k) space."},
    {"name":"Top K Frequent Elements","lc":347,"diff":"medium","tip":"Count frequencies (HashMap). Min-heap of size k by frequency. Or bucket sort by frequency. O(n log k) time."},
    {"name":"K Closest Points to Origin","lc":973,"diff":"medium","tip":"Max-heap of size k by distance. Pop when size>k. Remaining are k closest. O(n log k) time, O(k) space."},
    {"name":"Kth Largest Element in a Stream","lc":703,"diff":"easy","tip":"Min-heap of size k. On add: if size>k, pop min. Heap top = kth largest. O(log k) per add."},
    {"name":"Kth Smallest Element in a Sorted Matrix","lc":378,"diff":"medium","tip":"Binary search on value range, or min-heap starting with first column. Pop min, push next in row. O(n log(max-min))."},
    {"name":"Sort Characters By Frequency","lc":451,"diff":"medium","tip":"Count frequencies. Max-heap or bucket sort. Output chars in frequency order. O(n log n) time."},
    {"name":"Reorganize String","lc":767,"diff":"medium","tip":"Max-heap by frequency. Alternately place most frequent. Swap if consecutive same char would occur. O(n log n)."},
    {"name":"Last Stone Weight","lc":1046,"diff":"easy","tip":"Max-heap. Each turn: pop two heaviest, push |diff| if non-zero. Continue until <=1 stone. O(n log n) time."},
    {"name":"Minimum Cost to Connect Sticks","lc":1167,"diff":"medium","tip":"Min-heap: merge two smallest sticks each time. Cost = sum of merged pair (Huffman). O(n log n) time."},
    {"name":"Hand of Straights","lc":846,"diff":"medium","tip":"Sort or sorted map. Greedily form groups starting from smallest available. Count map decremented each group. O(n log n)."},
    {"name":"Car Pooling","lc":1094,"diff":"medium","tip":"Events: +passengers at start, -at end. Sort events by time. Running sum, check against capacity. O(n log n)."}
  ],"practice":[
    {"name":"Find Median from Data Stream","lc":295,"diff":"hard","tip":"Max-heap (lower half) + min-heap (upper half). Balance sizes. Median = top of larger or avg of both tops. O(log n) add."},
    {"name":"Merge K Sorted Lists","lc":23,"diff":"hard","tip":"Min-heap of (value, listIndex). Pop min, push next from same list. O(N log k) time where N=total nodes."},
    {"name":"Task Scheduler","lc":621,"diff":"medium","tip":"Max-heap by frequency. Schedule most frequent first. Count idles when no valid task. O(n log n) time."},
    {"name":"K Pairs with Smallest Sums","lc":373,"diff":"medium","tip":"Min-heap initialized with (nums1[i]+nums2[0], i, 0). Pop, add pair, push (nums1[i]+nums2[j+1], i, j+1). O(k log k)."},
    {"name":"The K Weakest Rows in a Matrix","lc":1337,"diff":"easy","tip":"Count soldiers per row (binary search). Max-heap of size k by (soldiers, index). O(m log n + m log k)."},
    {"name":"Smallest Range Covering Elements from K Lists","lc":632,"diff":"hard","tip":"Min-heap with one element per list. Replace min with next from same list. Track max in range. O(n log k)."},
    {"name":"Top K Frequent Words","lc":692,"diff":"medium","tip":"Count frequencies. Min-heap size k ordered by (-freq, word) for alphabetical tiebreak. O(n log k) time."},
    {"name":"Furthest Building You Can Reach","lc":1642,"diff":"medium","tip":"Min-heap of size ladders for largest climbs. When full and need ladder, use brick for smallest previous. O(n log l)."},
    {"name":"Seat Reservation Manager","lc":1845,"diff":"medium","tip":"Min-heap initialized with 1..n. Reserve: pop min seat. Unreserve: push back. O(log n) per op."},
    {"name":"Maximum Subsequence Score","lc":2542,"diff":"medium","tip":"Sort by second array descending. Min-heap for first array. Slide window of k: add to heap, remove smallest if >k. O(n log k)."},
    {"name":"Kth Largest Sum in a Binary Tree","lc":2583,"diff":"medium","tip":"BFS for level sums. Min-heap of size k. At end return top. O(n log k) time, O(n) space."},
    {"name":"Minimum Number of Refueling Stops","lc":871,"diff":"hard","tip":"Greedy: max-heap of fuel at passed stations. When out of fuel, retroactively take most fuel seen. O(n log n)."},
    {"name":"Single-Threaded CPU","lc":1834,"diff":"medium","tip":"Sort tasks by enqueue time. Min-heap by (processingTime, index). Simulate CPU, handle idle time. O(n log n)."},
    {"name":"Reduce Array Size to The Half","lc":1338,"diff":"medium","tip":"Count frequencies. Max-heap. Greedily remove most frequent until half removed. Count removals. O(n log n)."}
  ],"hard":[
    {"name":"Find Median from Data Stream","lc":295,"diff":"hard","tip":"Use two heaps: max-heap for lower half, min-heap for upper half. Balance so sizes differ by <=1. Median = top of larger heap or avg of both tops."},
    {"name":"Sliding Window Median","lc":480,"diff":"hard","tip":"Extend two-heap approach with lazy deletion. Mark removed elements in a set; count only elements still in window when reading medians."},
    {"name":"IPO","lc":502,"diff":"hard","tip":"Sort projects by capital. Use pointer to add all affordable projects to max-heap by profit. Greedily pick highest profit k times, updating capital."},
    {"name":"Minimum Number of Refueling Stops","lc":871,"diff":"hard","tip":"Greedy with max-heap. Travel as far as possible. When stuck, retroactively refuel from largest available station. O(n log n) time, O(n) space."},
    {"name":"Maximum Performance of a Team","lc":1383,"diff":"hard","tip":"Sort by efficiency descending. Min-heap for speeds of size k. For each engineer as min efficiency, maximize speed sum. O(n log k)."}
  ]},
  {"id":8,"name":"Overlapping Intervals","learn":[
    {"name":"Merge Intervals","lc":56,"diff":"medium","tip":"Sort by start. If current overlaps last (start<=last.end), extend last.end. Else add new. O(n log n) time, O(n) space."},
    {"name":"Insert Interval","lc":57,"diff":"medium","tip":"Add new interval. Merge overlapping: collect non-overlapping before, merge overlapping, append rest. O(n) time."},
    {"name":"Non-overlapping Intervals","lc":435,"diff":"medium","tip":"Sort by end. Greedy: keep interval with earliest end, remove overlapping. Count removals. O(n log n) time."},
    {"name":"Meeting Rooms","lc":252,"diff":"easy","tip":"Sort by start. Check if any meeting starts before previous ends. O(n log n) time, O(1) space."},
    {"name":"Meeting Rooms II","lc":253,"diff":"medium","tip":"Min-heap of end times. Each meeting: if start>=heap.top, pop. Always push end. Heap size = rooms needed. O(n log n)."},
    {"name":"Minimum Number of Arrows to Burst Balloons","lc":452,"diff":"medium","tip":"Sort by end. Shoot at each end point, bursting all overlapping. Count arrows. O(n log n) time, O(1) space."},
    {"name":"Car Pooling","lc":1094,"diff":"medium","tip":"Events: +passengers at pickup, -at dropoff. Sort by time. Running sum, check capacity. O(n log n) time."},
    {"name":"Remove Covered Intervals","lc":1288,"diff":"medium","tip":"Sort by start asc, end desc. Track max end seen. If current end<=max, it's covered. Count uncovered. O(n log n)."},
    {"name":"Interval List Intersections","lc":986,"diff":"medium","tip":"Two pointers. Intersection=[max(starts),min(ends)] if start<=end. Advance list with smaller endpoint. O(m+n)."},
    {"name":"Divide Intervals Into Minimum Number of Groups","lc":2406,"diff":"medium","tip":"Same as Meeting Rooms II: sort, min-heap of end times, track max concurrent. O(n log n) time."},
    {"name":"Count Ways to Group Overlapping Ranges","lc":2580,"diff":"medium","tip":"Sort, merge overlapping, count groups. Answer=2^groups mod 1e9+7. O(n log n) time, O(1) space."}
  ],"practice":[
    {"name":"Interval List Intersections","lc":986,"diff":"medium","tip":"Two pointers. Intersection=[max(a.start,b.start),min(a.end,b.end)] if valid. Advance list with smaller end. O(m+n)."},
    {"name":"Employee Free Time","lc":759,"diff":"hard","tip":"Flatten all intervals, sort by start. Walk through finding gaps between end of last and start of next. O(n log n)."},
    {"name":"My Calendar I","lc":729,"diff":"medium","tip":"TreeMap of start->end. Find floor and ceiling of new start. Check no overlap with neighbors. O(log n) per insert."},
    {"name":"My Calendar II","lc":731,"diff":"medium","tip":"Two TreeMaps: single and double bookings. Check against double first. Add overlaps to double, all to single. O(n) per."},
    {"name":"Count of Meetings in All Rooms","lc":2402,"diff":"medium","tip":"Min-heap of (endTime, roomIndex). Assign meeting to earliest-ending room. O(n log k) time, O(k) space."},
    {"name":"Divide Intervals Into Minimum Number of Groups","lc":2406,"diff":"medium","tip":"Sort by start. Min-heap of end times. Pop if start>top (reuse), push new end. Max heap size=answer. O(n log n)."},
    {"name":"Remove Covered Intervals","lc":1288,"diff":"medium","tip":"Sort start asc, end desc. Scan: if current end>max end seen, not covered, update max. Count non-covered. O(n log n)."},
    {"name":"Minimum Interval to Include Each Query","lc":1851,"diff":"hard","tip":"Sort intervals and queries. Min-heap (size, end). Add all intervals starting<=query. Remove ended. Answer=top. O((n+q) log n)."},
    {"name":"Number of Flowers in Full Bloom","lc":2251,"diff":"hard","tip":"Binary search: flowers started<=t minus flowers ended<t. Sort starts and ends. O((n+q) log n) time."},
    {"name":"Count Ways to Group Overlapping Ranges","lc":2580,"diff":"medium","tip":"Sort, merge overlapping intervals, count groups. 2^groups ways mod 1e9+7. O(n log n) time."},
    {"name":"My Calendar III","lc":732,"diff":"hard","tip":"Difference array with TreeMap. diff[start]++, diff[end]--. After each update sweep for max concurrent. O(n^2) per."},
    {"name":"Task Scheduler","lc":621,"diff":"medium","tip":"Max-heap by frequency. Schedule most frequent each slot. Count idles. Formula: max(n, (maxFreq-1)*(n+1)+count_maxFreq). O(n log n)."},
    {"name":"Average Waiting Time","lc":1701,"diff":"medium","tip":"Simulate: track current time. Each customer waits max(0, prevEnd-arrival). Update running average. O(n) time."},
    {"name":"Maximum Profit in Job Scheduling","lc":1235,"diff":"hard","tip":"Sort by end. DP: dp[i]=max(skip i, take i + dp[last non-overlapping]). Binary search for last non-overlapping. O(n log n)."}
  ],"hard":[
    {"name":"Employee Free Time","lc":759,"diff":"hard","tip":"Flatten all intervals, sort by start. Walk through and collect gaps between consecutive intervals. A gap [prev.end, curr.start] is a free time slot."},
    {"name":"Minimum Interval to Include Each Query","lc":1851,"diff":"hard","tip":"Sort intervals and queries. Process queries in sorted order. Use a min-heap of (size, end). Add intervals starting<=query, remove ended, answer=heap top."},
    {"name":"My Calendar III","lc":732,"diff":"hard","tip":"Use a difference array / TreeMap. For each booking [s,e]: diff[s]++ and diff[e]--. After each booking, sweep through and track running max of prefix sums."},
    {"name":"Number of Flowers in Full Bloom","lc":2251,"diff":"hard","tip":"Binary search: count flowers started<=query time minus flowers ended<query time. Sort starts and ends arrays. O((n+q) log n) time, O(n) space."},
    {"name":"Maximum Profit in Job Scheduling","lc":1235,"diff":"hard","tip":"DP + binary search. Sort by end. dp[i]=max(skip, take + dp[last non-overlapping]). Binary search for last non-overlapping job. O(n log n) time."}
  ]},
  {"id":9,"name":"Modified Binary Search","learn":[
    {"name":"Binary Search","lc":704,"diff":"easy","tip":"Classic: lo=0, hi=n-1. mid=(lo+hi)/2. Adjust lo/hi based on comparison. O(log n) time, O(1) space."},
    {"name":"Search Insert Position","lc":35,"diff":"easy","tip":"Binary search for target. If not found, lo = insertion position. Return lo after loop. O(log n) time."},
    {"name":"Find Minimum in Rotated Sorted Array","lc":153,"diff":"medium","tip":"If mid>right, minimum is in right half. Else in left. Converge to minimum element. O(log n) time."},
    {"name":"Search in Rotated Sorted Array","lc":33,"diff":"medium","tip":"Determine which half is sorted (compare mid with lo). If target in sorted half, search there; else other. O(log n)."},
    {"name":"Find Peak Element","lc":162,"diff":"medium","tip":"If nums[mid]<nums[mid+1], peak is on right; else on left or at mid. O(log n) time, O(1) space."},
    {"name":"Koko Eating Bananas","lc":875,"diff":"medium","tip":"Binary search on speed. Min=1, max=max(piles). For each speed, check if feasible in h hours. O(n log m)."},
    {"name":"Capacity To Ship Packages Within D Days","lc":1011,"diff":"medium","tip":"Binary search on capacity. Min=max weight, max=total. Check if D days feasible. O(n log sum) time."},
    {"name":"Guess Number Higher or Lower","lc":374,"diff":"easy","tip":"Binary search in 1..n. guess(mid)=0 correct, -1 lower, 1 higher. Adjust bounds. O(log n) time."},
    {"name":"First Bad Version","lc":278,"diff":"easy","tip":"Binary search: isBadVersion(mid)? If bad hi=mid; else lo=mid+1. Find leftmost bad. O(log n) time."},
    {"name":"Sqrt(x)","lc":69,"diff":"easy","tip":"Binary search for largest n where n*n<=x. Use long to avoid overflow. O(log x) time, O(1) space."},
    {"name":"Search a 2D Matrix","lc":74,"diff":"medium","tip":"Treat matrix as sorted array: index i -> matrix[i/cols][i%cols]. Standard binary search. O(log mn) time."}
  ],"practice":[
    {"name":"Find Minimum in Rotated Sorted Array II","lc":154,"diff":"hard","tip":"Like LC 153 with duplicates. When nums[lo]=nums[mid]=nums[hi], shrink both by 1. O(log n) avg, O(n) worst."},
    {"name":"Search in Rotated Sorted Array II","lc":81,"diff":"medium","tip":"Like LC 33 with duplicates. When nums[lo]=nums[mid], lo++. Otherwise standard rotated binary search. O(log n) avg."},
    {"name":"Find K Closest Elements","lc":658,"diff":"medium","tip":"Binary search for left boundary of window of size k. Compare arr[mid] vs arr[mid+k] distance to x. O(log n + k)."},
    {"name":"Split Array Largest Sum","lc":410,"diff":"hard","tip":"Binary search on answer. Check if feasible with <=m subarrays where each<=mid (greedy split). O(n log sum)."},
    {"name":"Time Based Key-Value Store","lc":981,"diff":"medium","tip":"HashMap<key, sorted list of (timestamp, value)>. Binary search for largest timestamp<=t. O(log n) per get."},
    {"name":"Find Right Interval","lc":436,"diff":"medium","tip":"Sort intervals by start. For each interval's end, binary search for smallest start>=end. O(n log n) time."},
    {"name":"Count of Smaller Numbers After Self","lc":315,"diff":"hard","tip":"Merge sort for inversion count. Or BIT: coordinate compress, process right-to-left. O(n log n) time."},
    {"name":"Maximum Value at a Given Index in a Bounded Array","lc":1802,"diff":"medium","tip":"Binary search on value at index. Min sum for given v = sum of decreasing slopes from both sides. O(log maxSum)."},
    {"name":"Minimum Speed to Arrive on Time","lc":1870,"diff":"medium","tip":"Binary search on speed. For each speed compute time (ceiling except last). Check<=hour. O(n log maxSpeed)."},
    {"name":"Arranging Coins","lc":441,"diff":"easy","tip":"Binary search for largest k with k(k+1)/2<=n. Or quadratic formula. O(log n) time, O(1) space."},
    {"name":"Valid Perfect Square","lc":367,"diff":"easy","tip":"Binary search: find if any m with m*m=num. Use long to avoid overflow. O(log n) time."},
    {"name":"Find Smallest Letter Greater Than Target","lc":744,"diff":"easy","tip":"Binary search for first letter>target. If none, wrap to first letter. O(log n) time, O(1) space."},
    {"name":"Random Pick with Weight","lc":528,"diff":"medium","tip":"Build prefix sum array. Random number in [0,total]. Binary search for first prefix>=random. O(log n) per pick."},
    {"name":"Kth Smallest Number in Multiplication Table","lc":668,"diff":"hard","tip":"Binary search on answer. Count numbers<=mid: sum of min(mid/i, n) for each row i. O(m log(mn)) time."}
  ],"hard":[
    {"name":"Find in Mountain Array","lc":1095,"diff":"hard","tip":"Binary search twice: find peak, then binary search ascending left side and descending right. Adjust comparators. O(log n)."},
    {"name":"Split Array Largest Sum","lc":410,"diff":"hard","tip":"Binary search on the answer (minimum largest sum). Check function: greedily partition into <=m subarrays each<=mid."},
    {"name":"Median of Two Sorted Arrays","lc":4,"diff":"hard","tip":"Binary search on smaller array to find correct partition. Ensure maxLeft1<=minRight2 and maxLeft2<=minRight1. O(log min(m,n))."},
    {"name":"Count of Range Sum","lc":327,"diff":"hard","tip":"Merge sort prefix sums. Count pairs in [lower,upper] during merge with two pointers. O(n log n) time, O(n) space."},
    {"name":"Kth Smallest Number in Multiplication Table","lc":668,"diff":"hard","tip":"Binary search on value. Count entries<=mid in m*n table: sum of min(mid/i, n) per row. O(m log(mn)) time, O(1) space."}
  ]},
  {"id":10,"name":"Tree Depth-First Search","learn":[
    {"name":"Maximum Depth of Binary Tree","lc":104,"diff":"easy","tip":"Return 1+max(leftDepth, rightDepth). Base: null returns 0. O(n) time, O(h) space."},
    {"name":"Path Sum","lc":112,"diff":"easy","tip":"Subtract node value from target, recurse. At leaf check if remaining=0. O(n) time, O(h) space."},
    {"name":"Same Tree","lc":100,"diff":"easy","tip":"Both null: true. One null: false. Values differ: false. Recurse both children. O(n) time, O(h) space."},
    {"name":"Invert Binary Tree","lc":226,"diff":"easy","tip":"Swap left and right children, recurse on both. O(n) time, O(h) space."},
    {"name":"Symmetric Tree","lc":101,"diff":"easy","tip":"Helper checks mirror: both null=true, equal values + recurse(left.left,right.right) and (left.right,right.left). O(n)."},
    {"name":"Count Good Nodes in Binary Tree","lc":1448,"diff":"medium","tip":"DFS passing max value on current path. Node is good if value>=maxSoFar. O(n) time, O(h) space."},
    {"name":"Diameter of Binary Tree","lc":543,"diff":"easy","tip":"At each node: diameter=leftHeight+rightHeight. Track global max. Return height=1+max(left,right). O(n) time."},
    {"name":"Minimum Depth of Binary Tree","lc":111,"diff":"easy","tip":"Special case: if only one child, go through non-null child. Min depth = min of non-null children + 1. O(n) time."},
    {"name":"Sum of Left Leaves","lc":404,"diff":"easy","tip":"DFS with flag for left child. Add value when node is leaf and flag is true. O(n) time, O(h) space."},
    {"name":"Binary Tree Paths","lc":257,"diff":"easy","tip":"DFS passing current path string. At leaf add to result. Add '->' between nodes. O(n) time, O(n) space."},
    {"name":"Balanced Binary Tree","lc":110,"diff":"easy","tip":"Return height; return -1 if unbalanced. If |left-right|>1, propagate -1 up. O(n) time, O(h) space."}
  ],"practice":[
    {"name":"Binary Tree Maximum Path Sum","lc":124,"diff":"hard","tip":"At each node: gain=node.val+max(0,left)+max(0,right). Update global max. Return node.val+max(0,max(left,right)). O(n)."},
    {"name":"Lowest Common Ancestor of a Binary Tree","lc":236,"diff":"medium","tip":"If current=p or q, return current. Both children non-null: current is LCA. Else return non-null child. O(n)."},
    {"name":"Construct Binary Tree from Preorder and Inorder Traversal","lc":105,"diff":"medium","tip":"Preorder[0]=root. Find root in inorder to split subtrees. HashMap for O(1) inorder lookup. O(n) time."},
    {"name":"Serialize and Deserialize Binary Tree","lc":297,"diff":"hard","tip":"Preorder with null markers. Serialize: 'val,null,...'. Deserialize: queue + recursive build from preorder. O(n)."},
    {"name":"Binary Tree Right Side View","lc":199,"diff":"medium","tip":"DFS with level. Last node visited at each level is visible. Or BFS taking last element per level. O(n) time."},
    {"name":"Sum Root to Leaf Numbers","lc":129,"diff":"medium","tip":"DFS passing running number. At leaf add to total. Running=prevNum*10+node.val. O(n) time, O(h) space."},
    {"name":"Path Sum II","lc":113,"diff":"medium","tip":"DFS with path list. At leaf if remaining=0, copy path to result. Backtrack by removing last. O(n) time."},
    {"name":"All Paths From Source to Target","lc":797,"diff":"medium","tip":"DFS from 0 to n-1. Backtrack. DAG: no cycle detection needed. O(2^n * n) time, O(n) space."},
    {"name":"Keys and Rooms","lc":841,"diff":"medium","tip":"DFS/BFS from room 0. Mark visited. Collect keys, unlock rooms. Return all rooms visited. O(n+k) time."},
    {"name":"Surrounded Regions","lc":130,"diff":"medium","tip":"DFS from border O-cells to mark safe. Convert remaining O to X, restore safe. O(mn) time."},
    {"name":"Count Sub Islands","lc":1905,"diff":"medium","tip":"DFS grid2 islands. If any cell is water in grid1, not sub-island. Track flag through DFS. O(mn) time."},
    {"name":"Find Eventual Safe States","lc":802,"diff":"medium","tip":"DFS states: 0=unvisited, 1=in-progress, 2=safe. Node safe if all paths lead to terminal. O(n+e) time."},
    {"name":"Flatten Binary Tree to Linked List","lc":114,"diff":"medium","tip":"Post-order or Morris: attach right subtree after rightmost of left subtree. Left=null, right=was-left. O(n)."},
    {"name":"House Robber III","lc":337,"diff":"medium","tip":"Each node returns (rob, skip). rob=val+left.skip+right.skip. skip=max(left)+max(right). O(n) time, O(h) space."}
  ],"hard":[
    {"name":"Longest Increasing Path in a Matrix","lc":329,"diff":"hard","tip":"DFS with memoization. From each cell explore 4 directions only if strictly increasing. Cache result — safe as paths are DAGs."},
    {"name":"Critical Connections in a Network","lc":1192,"diff":"hard","tip":"Tarjan's bridge-finding. Track disc[] and low[]. Edge (u,v) is bridge if low[v]>disc[u]: v can't reach u without this edge."},
    {"name":"Number of Distinct Islands","lc":694,"diff":"medium","tip":"DFS recording path signature (R,L,U,D + backtrack markers). Store unique signatures in HashSet. O(mn) time."},
    {"name":"Binary Tree Cameras","lc":968,"diff":"hard","tip":"DFS returning state: 0=needs camera, 1=covered, 2=has camera. Parent installs camera if child needs one. O(n) time."},
    {"name":"All Nodes Distance K in Binary Tree","lc":863,"diff":"medium","tip":"Build undirected graph from tree. BFS from target node to find all nodes at distance k. O(n) time, O(n) space."}
  ]},
  {"id":11,"name":"Tree/Graph DFS","learn":[
    {"name":"Number of Islands","lc":200,"diff":"medium","tip":"DFS from each unvisited '1'. Mark visited cells as '0'. Count DFS calls. O(mn) time, O(mn) space."},
    {"name":"Clone Graph","lc":133,"diff":"medium","tip":"DFS with HashMap original->clone. If clone exists, return it (handles cycles). Clone neighbors recursively. O(n+e)."},
    {"name":"Course Schedule","lc":207,"diff":"medium","tip":"Topological sort / cycle detection. DFS with colors: 0=unvisited, 1=in-progress, 2=done. Cycle if revisit in-progress. O(n+e)."},
    {"name":"Flood Fill","lc":733,"diff":"easy","tip":"DFS from start pixel. Change to new color. Visit 4-directional neighbors with original color. O(mn) time."},
    {"name":"Max Area of Island","lc":695,"diff":"medium","tip":"DFS from each unvisited '1'. Count cells in island. Track maximum. Mark visited. O(mn) time, O(mn) space."},
    {"name":"Pacific Atlantic Water Flow","lc":417,"diff":"medium","tip":"Reverse flow: BFS/DFS from Pacific edges and Atlantic edges separately. Cells in both = answer. O(mn) time."},
    {"name":"Is Graph Bipartite","lc":785,"diff":"medium","tip":"2-coloring with DFS/BFS. If adjacent nodes same color: not bipartite. O(n+e) time, O(n) space."},
    {"name":"Find if Path Exists in Graph","lc":1971,"diff":"easy","tip":"DFS/BFS from source. Mark visited. Return true if destination reached. Union-Find also works. O(n+e)."},
    {"name":"All Paths From Source to Target","lc":797,"diff":"medium","tip":"DFS from 0, backtrack. Add path when target reached. DAG: no cycle detection. O(2^n * n) time."},
    {"name":"Keys and Rooms","lc":841,"diff":"medium","tip":"DFS/BFS from room 0. Collect keys, unlock rooms. Check all rooms visited. O(n+k) time, O(n) space."},
    {"name":"Find Center of Star Graph","lc":1791,"diff":"easy","tip":"Center appears in every edge. Compare first two edges: shared node is center. O(1) time, O(1) space."}
  ],"practice":[
    {"name":"Course Schedule II","lc":210,"diff":"medium","tip":"Topological sort (Kahn's BFS or DFS post-order). Return order. Empty if cycle. O(n+e) time."},
    {"name":"Number of Connected Components in an Undirected Graph","lc":323,"diff":"medium","tip":"DFS/BFS or Union-Find. Count components. O(n+e) time, O(n) space."},
    {"name":"Graph Valid Tree","lc":261,"diff":"medium","tip":"Valid tree: n-1 edges, no cycles, connected. DFS cycle detection + connectivity. O(n+e) time."},
    {"name":"Redundant Connection","lc":684,"diff":"medium","tip":"Union-Find. For each edge: if nodes already connected, it's redundant. O(n*alpha(n)) time."},
    {"name":"Reconstruct Itinerary","lc":332,"diff":"hard","tip":"Hierholzer's for Eulerian path. DFS with sorted adjacency. Post-order insertion gives reverse itinerary. O(e log e)."},
    {"name":"Alien Dictionary","lc":269,"diff":"hard","tip":"Build directed graph from character ordering in adjacent words. Topological sort. Handle cycle (invalid). O(C) time."},
    {"name":"Word Ladder","lc":127,"diff":"hard","tip":"BFS with word transformation. Each step: try all one-letter changes. Use word set for O(1) lookup. O(m^2*n) time."},
    {"name":"Path Sum II","lc":113,"diff":"medium","tip":"DFS maintaining path list. At leaf matching target, record path copy. Backtrack. O(n^2) time worst case."},
    {"name":"All Paths From Source to Target","lc":797,"diff":"medium","tip":"DFS backtracking in DAG. No cycle detection needed. Collect all paths. O(2^n * n) time."},
    {"name":"Keys and Rooms","lc":841,"diff":"medium","tip":"DFS collecting keys. Mark rooms visited. All n rooms visited = true. O(n+k) time."},
    {"name":"Surrounded Regions","lc":130,"diff":"medium","tip":"DFS/BFS from border O-cells to mark safe. Flip remaining O to X. Restore safe. O(mn) time."},
    {"name":"Count Sub Islands","lc":1905,"diff":"medium","tip":"DFS on grid2. Sub-island if all cells also land in grid1. Mark cells visited during DFS. O(mn) time."},
    {"name":"Find Eventual Safe States","lc":802,"diff":"medium","tip":"Color-based DFS. Node safe if no cycle reachable. State 0=unvisited, 1=in-progress, 2=safe. O(n+e)."},
    {"name":"Time Needed to Inform All Employees","lc":1376,"diff":"medium","tip":"Build tree from manager relations. DFS: time for subtree=informTime[node]+max(children times). O(n) time."}
  ],"hard":[
    {"name":"Longest Increasing Path in a Matrix","lc":329,"diff":"hard","tip":"DFS with memoization on a DAG (strictly increasing). Memo each cell's longest path. No cycle issues since path is strictly increasing."},
    {"name":"Critical Connections in a Network","lc":1192,"diff":"hard","tip":"Tarjan's algorithm. low[v]>disc[u] means (u,v) is a bridge — no back edge from v's subtree reaches u or higher."},
    {"name":"Number of Distinct Islands","lc":694,"diff":"medium","tip":"DFS recording relative path shapes. Use start/end markers per direction to distinguish shapes. Store shapes in a set."},
    {"name":"Word Ladder II","lc":126,"diff":"hard","tip":"BFS to build layer graph (shortest paths). DFS/backtrack on layer graph to collect all shortest paths. O(m^2*n) time."},
    {"name":"Alien Dictionary","lc":269,"diff":"hard","tip":"Extract ordering constraints from adjacent words. Topological sort with DFS. Return empty if cycle or invalid prefix. O(C) time."}
  ]},
  {"id":12,"name":"BFS","learn":[
    {"name":"Binary Tree Level Order Traversal","lc":102,"diff":"medium","tip":"BFS with queue. Process level by level using size-based batching. O(n) time, O(n) space."},
    {"name":"Rotting Oranges","lc":994,"diff":"medium","tip":"Multi-source BFS from all rotten oranges. Spread each minute. Count fresh, check if all reached. O(mn) time."},
    {"name":"01 Matrix","lc":542,"diff":"medium","tip":"Multi-source BFS from all 0-cells. Distance = BFS level when first reached. O(mn) time, O(mn) space."},
    {"name":"Shortest Path in Binary Matrix","lc":1091,"diff":"medium","tip":"BFS from top-left. 8-directional movement. Level = path length. Return level at bottom-right. O(n^2) time."},
    {"name":"Walls and Gates","lc":286,"diff":"medium","tip":"Multi-source BFS from all gates (0-cells). BFS fills rooms with shortest distance. O(mn) time."},
    {"name":"Word Ladder","lc":127,"diff":"hard","tip":"BFS: each level=one transformation. Try all one-letter changes. Word set for O(1) removal. O(m^2*n) time."},
    {"name":"As Far from Land as Possible","lc":1162,"diff":"medium","tip":"Multi-source BFS from all land cells. Max BFS distance = answer. O(mn) time, O(mn) space."},
    {"name":"Average of Levels in Binary Tree","lc":637,"diff":"easy","tip":"BFS level order. For each level, average all node values. O(n) time, O(n) space."},
    {"name":"Binary Tree Zigzag Level Order Traversal","lc":103,"diff":"medium","tip":"BFS level order. Alternate direction each level. Use deque or reverse odd levels. O(n) time."},
    {"name":"Populating Next Right Pointers in Each Node","lc":116,"diff":"medium","tip":"BFS: for each node in queue, set next to next queue element at same level. Perfect tree allows O(1) space. O(n)."},
    {"name":"Symmetric Tree","lc":101,"diff":"easy","tip":"BFS: check pairs level by level. Queue pairs (left.left, right.right) and (left.right, right.left). O(n) time."}
  ],"practice":[
    {"name":"Minimum Depth of Binary Tree","lc":111,"diff":"easy","tip":"BFS finds first leaf node. Return level when first leaf found. Faster than DFS for unbalanced trees. O(n)."},
    {"name":"Jump Game III","lc":1306,"diff":"medium","tip":"BFS from index start. At each index explore i+arr[i] and i-arr[i]. Return true if 0 reached. O(n) time."},
    {"name":"Nearest Exit from Entrance in Maze","lc":1926,"diff":"medium","tip":"BFS from entrance. First non-entrance border cell found = nearest exit. O(mn) time, O(mn) space."},
    {"name":"Minimum Knight Moves","lc":1197,"diff":"medium","tip":"BFS with 8 knight moves. Visited set. Level = min moves. Use symmetry |x|,|y| to optimize. O(n^2) time."},
    {"name":"Open the Lock","lc":752,"diff":"medium","tip":"BFS on 4-digit states. Turn each wheel +-1. Skip deadends. Shortest path to target. O(10000) time."},
    {"name":"Snakes and Ladders","lc":909,"diff":"medium","tip":"BFS on board 1 to n^2. Map linear to (row,col). Apply snakes/ladders. BFS levels=dice rolls. O(n^2)."},
    {"name":"Shortest Bridge","lc":934,"diff":"medium","tip":"DFS to find first island. Multi-source BFS to expand toward second island. BFS level=bridge length. O(n^2)."},
    {"name":"Map of Highest Peak","lc":1765,"diff":"medium","tip":"Multi-source BFS from all water cells. Assign heights in BFS order (+1 each step). O(mn) time."},
    {"name":"Bus Routes","lc":815,"diff":"hard","tip":"BFS on bus routes not stops. Build stop->routes map. Start with routes containing source. O(n) time."},
    {"name":"Cut Off Trees for Golf Event","lc":675,"diff":"hard","tip":"Sort trees by height. BFS between consecutive trees for min steps. Sum all BFS distances. O(m^2*n^2) time."},
    {"name":"Cousins in Binary Tree","lc":993,"diff":"easy","tip":"BFS level order. Track parent and depth per node. Cousins = same depth, different parents. O(n) time."},
    {"name":"Find Largest Value in Each Tree Row","lc":515,"diff":"medium","tip":"BFS level order. Track max value per level. O(n) time, O(n) space."},
    {"name":"Check Completeness of a Binary Tree","lc":958,"diff":"medium","tip":"BFS. After first null, all subsequent nodes must be null. O(n) time, O(n) space."},
    {"name":"Maximum Depth of Binary Tree","lc":104,"diff":"easy","tip":"BFS counts levels. Return number of BFS levels = depth. O(n) time, O(n) space."}
  ],"hard":[
    {"name":"Word Ladder II","lc":126,"diff":"hard","tip":"BFS to find shortest path length and build layer graph. Then DFS/backtrack from end to start along BFS layer graph to collect all shortest paths."},
    {"name":"Minimum Cost to Make at Least One Valid Path in a Grid","lc":1368,"diff":"hard","tip":"0-1 BFS (deque). Moving in arrow direction costs 0 (push front), against costs 1 (push back). O(mn) time."},
    {"name":"Shortest Path to Get All Keys","lc":864,"diff":"hard","tip":"BFS with state=(row, col, keys_bitmask). Use visited set of (r,c,keys) to avoid revisiting. O(mn*2^k) time."},
    {"name":"Jump Game IV","lc":1345,"diff":"hard","tip":"BFS on index positions. Group same-value indices. From each position jump +-1 or to same-value group. Remove used groups. O(n)."},
    {"name":"Minimum Moves to Reach Target with Rotations","lc":1210,"diff":"hard","tip":"BFS with state (row,col,direction). Snake can move in 3 ways. Visited set of states. O(n^2) time."}
  ]},
  {"id":13,"name":"Matrix Traversal","learn":[
    {"name":"Number of Islands","lc":200,"diff":"medium","tip":"DFS/BFS from each unvisited '1'. Mark cells visited. Count traversals. O(mn) time, O(mn) space."},
    {"name":"Flood Fill","lc":733,"diff":"easy","tip":"DFS/BFS from start. Replace original color with new. Visit 4-connected same-color neighbors. O(mn) time."},
    {"name":"Max Area of Island","lc":695,"diff":"medium","tip":"DFS from each '1'. Count connected cells. Track maximum. Mark visited. O(mn) time, O(mn) space."},
    {"name":"Surrounded Regions","lc":130,"diff":"medium","tip":"DFS from border O-cells to mark safe. Flip remaining O to X, restore safe. O(mn) time."},
    {"name":"Pacific Atlantic Water Flow","lc":417,"diff":"medium","tip":"Reverse DFS: from Pacific borders and Atlantic borders. Cells reachable from both = answer. O(mn) time."},
    {"name":"Word Search","lc":79,"diff":"medium","tip":"DFS with backtracking. Mark cell '#', explore 4 directions, restore after backtrack. O(mn * 4^L) time."},
    {"name":"Number of Closed Islands","lc":1254,"diff":"medium","tip":"First DFS border-connected islands (not closed). Count remaining island components. O(mn) time."},
    {"name":"Island Perimeter","lc":463,"diff":"easy","tip":"For each land cell: count 4-directional neighbors that are water or out-of-bounds. Sum = perimeter. O(mn)."},
    {"name":"Coloring A Border","lc":1034,"diff":"medium","tip":"DFS to find all component cells. Mark border cells (adjacent to different color or edge). Recolor. O(mn) time."},
    {"name":"Number of Enclaves","lc":1020,"diff":"medium","tip":"DFS/BFS from border land cells to mark reachable. Count unreachable land cells = enclaves. O(mn) time."},
    {"name":"Count Sub Islands","lc":1905,"diff":"medium","tip":"DFS grid2 islands. Island is sub-island if all its cells are also land in grid1. O(mn) time, O(mn) space."}
  ],"practice":[
    {"name":"Shortest Path in Binary Matrix","lc":1091,"diff":"medium","tip":"BFS 8-directional from (0,0). Level=path length. Return level at (n-1,n-1). Return -1 if unreachable. O(n^2)."},
    {"name":"01 Matrix","lc":542,"diff":"medium","tip":"Multi-source BFS from all 0s. Each cell distance = BFS level when first visited. O(mn) time."},
    {"name":"Count Sub Islands","lc":1905,"diff":"medium","tip":"DFS grid2. If any land cell is also water in grid1, whole island not sub-island. Use return flag. O(mn)."},
    {"name":"Rotting Oranges","lc":994,"diff":"medium","tip":"Multi-source BFS from all (2)s. Count fresh. Spread minute by minute. Check all reached. O(mn) time."},
    {"name":"Map of Highest Peak","lc":1765,"diff":"medium","tip":"Multi-source BFS from water cells. Assign heights in order (+1 each step). Maximizes min adjacent diff. O(mn)."},
    {"name":"Number of Enclaves","lc":1020,"diff":"medium","tip":"BFS/DFS from border land. Mark connected land. Count unmarked land cells. O(mn) time, O(mn) space."},
    {"name":"Island Perimeter","lc":463,"diff":"easy","tip":"4*landCount - 2*adjacentLandPairs. Or per-cell approach counting water/boundary neighbors. O(mn) time."},
    {"name":"Number of Distinct Islands","lc":694,"diff":"medium","tip":"DFS path encoding. Normalize shape. HashSet of shapes. O(mn) time, O(mn) space."},
    {"name":"Minimum Number of Days to Disconnect Island","lc":1568,"diff":"hard","tip":"Answer is 0 (already), 1 (remove articulation point), or 2. Check with DFS/BFS each case. O(mn) time."},
    {"name":"Making A Large Island","lc":827,"diff":"hard","tip":"Label islands with unique IDs and sizes. For each 0-cell sum unique neighbor island sizes +1. O(mn) time."},
    {"name":"Spiral Matrix","lc":54,"diff":"medium","tip":"Four boundaries: top/bottom/left/right. Traverse right/down/left/up. Shrink boundaries. O(mn) time."},
    {"name":"Rotate Image","lc":48,"diff":"medium","tip":"Transpose (swap [i][j] and [j][i]) then reverse each row. In-place. O(n^2) time, O(1) space."},
    {"name":"Set Matrix Zeroes","lc":73,"diff":"medium","tip":"Use first row and column as flags. Two passes: mark then zero. Handle first row/col separately. O(mn) time."},
    {"name":"Search a 2D Matrix II","lc":240,"diff":"medium","tip":"Start at top-right. If target<current: move left. If target>current: move down. O(m+n) time, O(1) space."}
  ],"hard":[
    {"name":"Longest Increasing Path in a Matrix","lc":329,"diff":"hard","tip":"DFS + memoization. Since paths are strictly increasing, no cycles — memo is safe. Try all 4 directions, cache longest path per cell."},
    {"name":"Making A Large Island","lc":827,"diff":"hard","tip":"Label each island with unique ID and store its size. For each 0-cell look at 4 neighbors, sum unique island IDs' sizes + 1. Take max."},
    {"name":"Zuma Game","lc":488,"diff":"hard","tip":"BFS/DFS + memoization on (board_state, hand_state). Try inserting each ball at each position. Prune impossible states early."},
    {"name":"Word Search II","lc":212,"diff":"hard","tip":"Trie + DFS backtracking. Build Trie from words. DFS on grid following Trie. When word found, add to result. Remove found words for pruning."},
    {"name":"Number of Ways to Stay in the Same Place After Some Steps","lc":1269,"diff":"hard","tip":"DP: dp[steps][pos]=ways. Transitions: left/right/stay. Max useful pos=min(arrLen,steps). O(steps*arrLen) time."}
  ]},
  {"id":14,"name":"Backtracking","learn":[
    {"name":"Subsets","lc":78,"diff":"medium","tip":"For each element: include or exclude. DFS with start index. Add current path at every call. O(2^n * n) time."},
    {"name":"Permutations","lc":46,"diff":"medium","tip":"Swap-based or visited array. Try all unused elements at each position. Backtrack by unswapping. O(n! * n) time."},
    {"name":"Combination Sum","lc":39,"diff":"medium","tip":"DFS with start index. Same element reusable. Branch: include (stay at i) or skip (i+1). Prune if sum>target. O(n^(t/m))."},
    {"name":"Generate Parentheses","lc":22,"diff":"medium","tip":"Track open and close counts. Add '(' if open<n, ')' if close<open. Catalan number solutions: O(4^n/sqrt(n))."},
    {"name":"Letter Combinations of a Phone Number","lc":17,"diff":"medium","tip":"DFS with digit index. At each level try all letters for current digit. Backtrack. O(4^n * n) time."},
    {"name":"Subsets II","lc":90,"diff":"medium","tip":"Sort input. Skip duplicates: if i>start and nums[i]==nums[i-1], skip. Otherwise same as Subsets. O(2^n * n)."},
    {"name":"Permutations II","lc":47,"diff":"medium","tip":"Sort input. Visited array. Skip if nums[i]==nums[i-1] and !visited[i-1]. O(n! * n) time."},
    {"name":"Binary Watch","lc":401,"diff":"easy","tip":"Backtracking or bit counting. For each time 0:00-11:59, count bits. If count==num, add. O(1) fixed range."},
    {"name":"Beautiful Arrangement","lc":526,"diff":"medium","tip":"Backtracking: at position i, integer n valid if n%i==0 or i%n==0. Try all unused integers. O(k) permutations."},
    {"name":"Combinations","lc":77,"diff":"medium","tip":"DFS with start index and remaining count k. Add path when k elements collected. Prune when insufficient. O(C(n,k)*k)."},
    {"name":"Numbers With Same Consecutive Differences","lc":967,"diff":"medium","tip":"BFS/DFS starting each digit 1-9. Append digit+-k if valid (0-9). O(2^n * 9) time."}
  ],"practice":[
    {"name":"Combination Sum II","lc":40,"diff":"medium","tip":"Sort. Skip duplicates at same level (i>start and nums[i]==nums[i-1]). Each element once. O(2^n) time."},
    {"name":"Palindrome Partitioning","lc":131,"diff":"medium","tip":"DFS: try all palindrome substrings from current position. Backtrack. Precompute palindromes with DP. O(n*2^n)."},
    {"name":"Word Search","lc":79,"diff":"medium","tip":"DFS with backtracking. Mark cell visited, explore 4 directions, restore after backtrack. O(mn*4^L) time."},
    {"name":"N-Queens","lc":51,"diff":"hard","tip":"DFS row by row. Track attacked columns, diagonals (r-c), anti-diagonals (r+c). Backtrack. O(n!) time."},
    {"name":"Combinations","lc":77,"diff":"medium","tip":"Start index prevents duplicates. Prune when remaining > n-start+1. O(C(n,k)) time."},
    {"name":"Path Sum II","lc":113,"diff":"medium","tip":"DFS maintaining path. At leaf with target sum, save copy. Backtrack by removing last. O(n^2) time."},
    {"name":"Restore IP Addresses","lc":93,"diff":"medium","tip":"4 segments, each 1-3 digits, valid 0-255, no leading zeros. DFS with segment count. O(3^4)=O(1)."},
    {"name":"Expression Add Operators","lc":282,"diff":"hard","tip":"DFS with eval and last multiplicand. For *: eval = eval-last + last*cur. Handle leading zeros. O(4^n * n) time."},
    {"name":"Letter Case Permutation","lc":784,"diff":"medium","tip":"DFS: at each letter try both cases. Digits kept as-is. O(2^n * n) time, O(n) space."},
    {"name":"Sudoku Solver","lc":37,"diff":"hard","tip":"DFS: find empty cell, try 1-9. Check row/col/box validity. Backtrack if stuck. O(9^empty) time."},
    {"name":"Find Unique Binary String","lc":1980,"diff":"medium","tip":"Cantor's diagonal: i-th char differs from i-th char of nums[i]. Guaranteed unique. O(n) time."},
    {"name":"Maximum Length of a Concatenated String with Unique Characters","lc":1239,"diff":"medium","tip":"DFS/backtracking. Only concatenate if no char overlap. Bitmask for O(1) overlap check. O(2^n * n)."},
    {"name":"Split a String Into the Max Number of Unique Substrings","lc":1593,"diff":"medium","tip":"Backtracking: try all substrings as next split. HashSet ensures uniqueness. Maximize count. O(n!*n) worst."},
    {"name":"Count Numbers with Unique Digits","lc":357,"diff":"medium","tip":"DP: f(n)=9*9*8*...*(10-n+1) for n-digit numbers. Sum for 0 to n. O(1) since n<=10."}
  ],"hard":[
    {"name":"N-Queens II","lc":52,"diff":"hard","tip":"Track attacked columns, diagonals (r-c), and anti-diagonals (r+c) with sets. At each row try valid columns only. Count solutions."},
    {"name":"Word Search II","lc":212,"diff":"hard","tip":"Build a Trie from all words. DFS on grid, traverse Trie simultaneously. When Trie node has word ending, record it. Prune with marker."},
    {"name":"Regular Expression Matching","lc":10,"diff":"hard","tip":"Backtracking or DP. For '*': skip pattern (zero) or consume char if matches p[i-1]. DP[i][j]=does s[0..i] match p[0..j]?"},
    {"name":"Wildcard Matching","lc":44,"diff":"hard","tip":"DP: dp[i][j]=s[0..i-1] matches p[0..j-1]. '*' matches empty (dp[i][j-1]) or any sequence (dp[i-1][j]). O(mn)."},
    {"name":"Concatenated Words","lc":472,"diff":"hard","tip":"For each word check if formable by 2+ shorter words. Build Trie or use word set. DFS/DP per word. O(n*L^2) time."}
  ]},
  {"id":15,"name":"Dynamic Programming","learn":[
    {"name":"Climbing Stairs","lc":70,"diff":"easy","tip":"dp[i]=dp[i-1]+dp[i-2]. Base: dp[1]=1, dp[2]=2. Fibonacci pattern. O(n) time, O(1) space."},
    {"name":"House Robber","lc":198,"diff":"medium","tip":"dp[i]=max(dp[i-1], dp[i-2]+nums[i]). Can't rob adjacent. Two rolling variables. O(n) time, O(1) space."},
    {"name":"Coin Change","lc":322,"diff":"medium","tip":"dp[amount]=min coins. For each coin c: dp[i]=min(dp[i], dp[i-c]+1). Bottom-up. O(amount*coins) time."},
    {"name":"Longest Common Subsequence","lc":1143,"diff":"medium","tip":"If s1[i]=s2[j]: dp[i][j]=dp[i-1][j-1]+1. Else max(dp[i-1][j], dp[i][j-1]). O(mn) time and space."},
    {"name":"Longest Increasing Subsequence","lc":300,"diff":"medium","tip":"dp[i]=LIS ending at i. For j<i: if nums[j]<nums[i], dp[i]=max(dp[i],dp[j]+1). O(n^2) or O(n log n) with patience sorting."},
    {"name":"Unique Paths","lc":62,"diff":"medium","tip":"dp[i][j]=dp[i-1][j]+dp[i][j-1]. Border=1. O(mn) time, O(n) space with rolling array."},
    {"name":"Jump Game","lc":55,"diff":"medium","tip":"Greedy: track maxReachable. If current>maxReachable can't proceed. O(n) time, O(1) space."},
    {"name":"Fibonacci Number","lc":509,"diff":"easy","tip":"F(n)=F(n-1)+F(n-2). Two rolling variables. O(n) time, O(1) space."},
    {"name":"Min Cost Climbing Stairs","lc":746,"diff":"easy","tip":"dp[i]=cost[i]+min(dp[i-1],dp[i-2]). Answer=min(dp[n-1],dp[n-2]). O(n) time, O(1) space."},
    {"name":"N-th Tribonacci Number","lc":1137,"diff":"easy","tip":"T(n)=T(n-1)+T(n-2)+T(n-3). Three rolling variables. O(n) time, O(1) space."},
    {"name":"Pascal's Triangle","lc":118,"diff":"easy","tip":"Each row: first/last=1, middle=sum of two above. Build row by row. O(n^2) time and space."}
  ],"practice":[
    {"name":"Edit Distance","lc":72,"diff":"medium","tip":"dp[i][j]=min edits for s[0..i] to t[0..j]. Match: dp[i-1][j-1]. Else: 1+min(insert,delete,replace). O(mn)."},
    {"name":"Partition Equal Subset Sum","lc":416,"diff":"medium","tip":"0/1 knapsack: can we pick subset summing to total/2? dp[i]=reachable with sum i. Iterate in reverse. O(n*sum)."},
    {"name":"House Robber II","lc":213,"diff":"medium","tip":"Circular: run House Robber twice (exclude first, exclude last). Take max. O(n) time, O(1) space."},
    {"name":"Decode Ways","lc":91,"diff":"medium","tip":"dp[i]=ways to decode s[0..i-1]. One digit (1-9): +dp[i-1]. Two digits (10-26): +dp[i-2]. O(n) time."},
    {"name":"Word Break","lc":139,"diff":"medium","tip":"dp[i]=can s[0..i] be segmented. For j<i: if dp[j] and s[j..i] in dict, dp[i]=true. O(n^2*m) time."},
    {"name":"Maximum Product Subarray","lc":152,"diff":"medium","tip":"Track max and min products ending at i. dp[i]=max(nums[i], nums[i]*maxPrev, nums[i]*minPrev). O(n) time."},
    {"name":"Coin Change II","lc":518,"diff":"medium","tip":"Unbounded knapsack: dp[amount]=ways. For each coin: dp[j]+=dp[j-coin]. O(n*amount) time."},
    {"name":"Longest Palindromic Subsequence","lc":516,"diff":"medium","tip":"If s[i]==s[j]: dp[i][j]=dp[i+1][j-1]+2. Else max(dp[i+1][j],dp[i][j-1]). O(n^2) time."},
    {"name":"Target Sum","lc":494,"diff":"medium","tip":"P-N=target, P+N=total -> P=(total+target)/2. Count subsets summing to P. 0/1 knapsack. O(n*sum)."},
    {"name":"Minimum Path Sum","lc":64,"diff":"medium","tip":"dp[i][j]=grid[i][j]+min(dp[i-1][j],dp[i][j-1]). In-place modification. O(mn) time, O(1) space."},
    {"name":"Counting Bits","lc":338,"diff":"easy","tip":"dp[i]=dp[i>>1]+(i&1). Even: same bits as half. Odd: half's bits plus 1. O(n) time, O(n) space."},
    {"name":"Maximum Subarray","lc":53,"diff":"medium","tip":"Kadane's: currSum=max(nums[i], currSum+nums[i]). Track global max. O(n) time, O(1) space."},
    {"name":"Best Time to Buy and Sell Stock","lc":121,"diff":"easy","tip":"Track min price seen. Max profit=max(profit, price-minPrice). O(n) time, O(1) space."},
    {"name":"Best Time to Buy and Sell Stock with Cooldown","lc":309,"diff":"medium","tip":"States: held/sold(cooldown)/rest. Transitions via state machine. O(n) time, O(1) space."}
  ],"hard":[
    {"name":"Burst Balloons","lc":312,"diff":"hard","tip":"Think backwards: last balloon popped in [i,j] is k. dp[i][j]=max(nums[i-1]*nums[k]*nums[j+1]+dp[i][k-1]+dp[k+1][j])."},
    {"name":"Regular Expression Matching","lc":10,"diff":"hard","tip":"dp[i][j]=s[0..i-1] matches p[0..j-1]. For '*': dp[i][j]=dp[i][j-2] (skip) OR (s[i]==p[j-1] and dp[i-1][j]) (extend)."},
    {"name":"Edit Distance","lc":72,"diff":"hard","tip":"Classic Levenshtein: if chars match dp[i][j]=dp[i-1][j-1]. Else 1+min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]) = delete/insert/replace."},
    {"name":"Longest Valid Parentheses","lc":32,"diff":"hard","tip":"DP: dp[i]=length of longest valid ending at i. If s[i-dp[i-1]-1]=='(': dp[i]=dp[i-1]+2+dp[i-dp[i-1]-2]. O(n) time."},
    {"name":"Palindrome Partitioning II","lc":132,"diff":"hard","tip":"dp[i]=min cuts for s[0..i]. For each palindrome s[j..i]: dp[i]=min(dp[i],dp[j-1]+1). Precompute palindromes. O(n^2)."}
  ]}
]

print(json.dumps({"ok": len(patterns), "total_problems": sum(len(p["learn"])+len(p["practice"])+len(p["hard"]) for p in patterns)}))
